name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-build-and-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Animesh-Ghosh/Animesh-Ghosh.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && NODE_OPTIONS=--openssl-legacy-provider yarn build
        BUILD_DIR: ./docs/.vuepress/dist
